spring.application.name=backend

# Conexión a Neon
spring.datasource.url=jdbc:postgresql://ep-green-smoke-ai21o0uf.c-4.us-east-1.aws.neon.tech/bancodigital?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7qIHY9oGTSLM

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server.port=8080